
name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2 # v3.5.3
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Compile
        run: mvn clean install -DskipTests -pl byte-buddy-dep -am

      - name: compile without nondex
        run: mvn -pl byte-buddy-dep test -Dtest=net.bytebuddy.implementation.auxiliary.MethodCallProxyTest#testNonGenericParameter

