
name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 1"
permissions: read-all
jobs:
  hotspot-ea:
    name: HotSpot (EA)
    runs-on: ubuntu-latest
    needs: [ extended ]
    continue-on-error: true
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
        with:
          java-version: 11-ea
          distribution: zulu
          cache: maven
      - name: Build project
        run: mvn verify
        continue-on-error: true
  hotspot-supported:
    name: Any (supported)
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, macos-11, windows-2022 ]
        java: [ 8, 11, 17 ]
    runs-on: ${{ matrix.os }}
    needs: [ extended ]
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          architecture: x64
          cache: maven

      - name: Compile
        run: mvn clean install -DskipTests -pl byte-buddy-dep -am

      - name: compile without nondex
        run: mvn -pl byte-buddy-dep test -Dtest=net.bytebuddy.implementation.auxiliary.MethodCallProxyTest#testNonGenericParameter

